### ISSUE TITLE
Opponent Played Twice

### ISSUE THREAD

**Issue by fjcamillo** [VictorEvan/Tic-Tac-Toe#1]
Played with one player and chose `X`. Clicked as soon as the grid turned blue. Here's an image of what happened

![screenshot from 2018-06-17 20-27-00](https://user-images.githubusercontent.com/12166244/41507842-431ee472-726d-11e8-9786-92f3cb7731d7.png)

**Comment by victorevan** [comment]
![tictactoeglitch](https://user-images.githubusercontent.com/31473753/42429759-d942e312-82ef-11e8-938c-7de4a3225876.PNG)

I was able to replicate the issue by clicking immediately as well. Thanks for the heads up. I'll check out what's going on.

**Comment by victorevan** [comment]
It seems that in the corner case where a user clicks rapidly on tiles, actions were able to dispatched multiple times which broke the app. I've added additional conditional code blocks that will prevent the user from triggering an action dispatch at unintended times. Additionally, the application will now be able to tell if a user is clicking on a tile that has already been filled, which will also further prevent needless action dispatching.
